default-radius: 5 # Default radius of containers in Blocks (dropchest.radius.set) to let users set their own radius
max-radius: 10 # Maximum radius of containers in Blocks (dropchest.radius.unlimited) to let users exceed this limit
poll-interval: 1 # Interval to poll for items to add to containers (in ticks)
wait-for-pickup: false # Allow players to pick up items before the chest?
allow-protect: true # Allow players to protect containers?
default-protect: false # Protect containers by default?